experiment_name: "experiment"
list_velocity_files: "path/to/file.txt"
list_coordinate_files: "path/to/file.txt"
list_particle_files: "path/to/file.txt"
snapshot_timestep: 0.1
flow_map_period: 5
integrator: rk4
interpolator: cubic
num_processes: 8
output_format: "vtk"
grid_shape: 100, 100, 100  # comment this line for unstructured data
