[files]
extend-exclude = [".git/", ".tox/", ".venv/", "docs/", "joss-paper/"]

[default.extend-identifiers]
LinearNDInterpolator = "LinearNDInterpolator"
NearestNDInterpolator = "NearestNDInterpolator"
