name: Python Code Style
on: [push]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Generate UV Lock file (if not already committed)
        run: uv lock --locked
  linting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Dev Dependencies
        shell: bash
        run: |
          uv sync
          uv pip install -e '.[dev]'
      - name: Run Ruff Check
        run: uv run ruff check src/ tests/
  formatting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Dev Dependencies
        shell: bash
        run: |
          uv sync
          uv pip install -e '.[dev]'
      - name: Run Ruff Format Check
        run: uv run ruff format --check src/ tests/
  type_consistency:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Dev Dependencies
        shell: bash
        run: |
          uv sync
          uv pip install -e '.[dev]'
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV
      - name: Run Pyright
        run: uv run pyright src/
  checking_typos:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Dev Dependencies
        shell: bash
        run: |
          uv sync
          uv pip install -e '.[dev]'
      - name: Run Typos Check
        run: uv run typos src/ tests/
