name: Python Tests
on: [push]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Generate UV Lock file (if not already committed)
        run: uv lock --locked

  tests:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create Virtual Environment and Install Dependencies
        shell: bash
        run: |
          uv sync
          uv pip install -e '.[dev,test]'
          uv pip list

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Tests
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
